<?php
#Author: Sunnefa Lind
#Project: Icontastic
#Date: 15.05.2011

/*
* This is theme_master.php - It holds the master templates for everything
* Please do not edit this file. Edit your themes theme.php file instead
* This file serves as a backup if any of the templates are not found in the current theme's theme.php file
*/


//before the user list
if(!isset($before_user_list_template)) {
	
	$before_user_list_template = <<<EOT
	<h1>{USERS}</h1>
EOT;
	
}

//the user list template
if(!isset($user_list_template)) {	
	$user_list_template = <<<EOT
	<p><a href="?page=user&id={U_ID}">{U_NAME}</a> - {REG_SINCE} {U_DATE} - {NUM_ICONS} {ICONS}</p>
EOT;

}

//sinlge user display template
if(!isset($single_user_template)) {	
	$single_user_template = <<<EOT
<h1>{U_NAME}</h1>
	<p>{REG_SINCE} {U_DATE}</p>
	<p>{U_NAME} {U_UPLOADED_TEXT} {NUM_ICONS} {ICONS}<p>
	<p>{U_NAME} {U_CREATED_TEXT} {NUM_CATS} {CATEGORIES}</p>
EOT;

}

//single user block template
if(!isset($single_user_block_template)) {
	$single_user_block_template = <<<EOT

<div class="single_user">
	{USER_LIST}
</div>
EOT;
	
}

//before the category list
if(!isset($before_category_list_template)) {
	$before_category_list_template = <<<EOT
<h2>{CATEGORIES}</h2>
EOT;

}

//the single category display
if(!isset($single_category_template)) {	
	$single_category_template = <<<EOT
<div class="single_cat">
	<h1>{C_NAME}</h1>
	<p>{C_DESC}</p>
	</div>
	
EOT;

}

//the category list template
if(!isset($category_list_template)) {	
	$category_list_template = <<<EOT
	
	<a href="?page=cat&id={C_ID}">{C_NAME}</a> ({NUM_ICONS} {ICONS})
	<p>{C_DESC}</p>
EOT;

}

//category blcok template for category list
//the before unsorted icons template
if(!isset($category_list_block_template)) {
	$category_list_block_template = <<<EOT

<div class="category_list">
	{BEFORE_CATEGORY_LIST}
	{CAT_LIST}
</div>
EOT;

}

//the before unsorted icons template
if(!isset($before_unsorted_icons_template)) {
	$before_unsorted_icons_template = <<<EOT
<h2>{UNSORTED} {ICONS}</h2>
EOT;

}

//the icon list template
if(!isset($icon_list_template)) {
	$icon_list_template = <<<EOT
<div>
		<p><img src="{I_PATH}" /></p>
		<p>{U_LOADED_ON} {I_DATE}</p>
	</div>
	
EOT;

}

//the icon block template
if(!isset($icon_block_template)) {
	$icon_block_template = <<<EOT

<div class="icon_list">
	{BEFORE_ICONS}
	{ICON_LIST}
</div>
EOT;

}

?>